// Optional real-browser acceptance run. No browser dependency is shipped to students.
// Set PLAYWRIGHT_MODULE to a locally installed playwright module if necessary.
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { serve } from './server.mjs';
import { config, plan } from './fixtures.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { server, url } = await serve();
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
const output = new URL('../test-results/', import.meta.url); await fs.mkdir(output, { recursive: true });
const errors = [], requests = [], results = [];
let context;
const pass = text => { results.push(text); console.log('PASS ' + text); };
try {
  context = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'America/Toronto', reducedMotion: 'reduce', permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message)); context.on('request', r => requests.push({ url: r.url(), method: r.method(), body: r.postData() }));
  const click = async name => {
    const locator = page.getByRole('button', { name, exact: true }), handle = await locator.elementHandle();
    await locator.click();
    await page.waitForFunction(b => !b.isConnected || !b.disabled || document.querySelector('dialog[open]'), handle);
    await handle.dispose();
  };
  const heading = name => page.getByRole('heading', { name, exact: true }).waitFor();
  await page.goto(url); await heading('Build Your Own Goal Tracker');
  assert.ok((await page.locator('main').innerText()).includes('Age 13+'));
  await page.keyboard.press('Tab'); assert.equal(await page.locator(':focus').innerText(), 'Skip to main content');
  await page.keyboard.press('Enter'); assert.equal(await page.locator(':focus').getAttribute('id'), 'main');
  assert.equal(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches), true);
  await page.screenshot({ path: new URL('welcome-mobile.png', output).pathname.replace(/^\/(?=[A-Za-z]:)/, ''), fullPage: true });
  pass('Fresh start, age guidance, keyboard skip link, reduced motion and mobile welcome');
  await click("I'M A TEACHER"); await heading('A small project in student agency'); await click('BACK');
  await click('BUILD MY TRACKER'); await click("I Don't Know Yet"); await click('GIVE ME IDEAS');
  assert.ok((await page.locator('main').innerText()).includes('summarize what you read'));
  await page.getByLabel('Your answer', { exact: true }).fill(plan().answers.goal); await click('NEXT');
  await page.getByLabel('Your answer', { exact: true }).fill(plan().answers.why); await click('BACK');
  assert.equal(await page.getByLabel('Your answer', { exact: true }).inputValue(), plan().answers.goal);
  await page.reload(); assert.equal(await page.getByLabel('Your answer', { exact: true }).inputValue(), plan().answers.goal);
  await click('NEXT'); assert.equal(await page.getByLabel('Your answer', { exact: true }).inputValue(), plan().answers.why);
  await click('NEXT');
  for (const key of ['success', 'time', 'actions', 'easy', 'effort']) { await page.getByLabel('Your answer', { exact: true }).fill(plan().answers[key]); await click('NEXT'); }
  for (const d of ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']) await page.getByLabel(d, { exact: true }).check();
  await click('NEXT');
  for (const key of ['feel', 'name']) { await page.getByLabel('Your answer', { exact: true }).fill(plan().answers[key]); await click('NEXT'); }
  await heading('Your Goal Plan');
  pass('Unknown-goal discovery, ten-question builder, Back, draft refresh, schedule and review');
  await click('LOOKS GOOD'); await click('COPY MY AI PROMPT');
  const prompt = await page.evaluate(() => navigator.clipboard.readText());
  assert.match(prompt, /Do NOT write HTML/); assert.ok(prompt.includes(plan().answers.goal)); assert.match(prompt, /scheduledDays/);
  await click('I HAVE MY TRACKER SETUP');
  const paste = page.getByLabel('Tracker Setup from your AI conversation');
  await paste.fill('{broken'); await click('BUILD MY TRACKER'); await heading('Almost there.');
  await click('COPY FIX PROMPT'); assert.match(await page.evaluate(() => navigator.clipboard.readText()), /corrected COMPLETE/);
  const hostile = config(); hostile.mainGoal = '<img src=x onerror="window.pwned=true">';
  await paste.fill(JSON.stringify(hostile)); await click('BUILD MY TRACKER');
  assert.equal(await page.evaluate(() => window.pwned), undefined); assert.equal(await page.locator('main img').count(), 0);
  await paste.fill('x'.repeat(24001)); await click('BUILD MY TRACKER'); await heading('Almost there.');
  await paste.fill('Your setup:\n```json\n' + JSON.stringify(config()) + '\n```'); await click('BUILD MY TRACKER'); await heading('Does this tracker work for you?');
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('universalGoalTracker:state:v1')).trackerConfig), null);
  await page.screenshot({ path: new URL('preview-mobile.png', output).pathname.replace(/^\/(?=[A-Za-z]:)/, ''), fullPage: true });
  await click('SAVE TRACKER'); await heading('Practice Lab');
  pass('Approved deterministic clipboard prompt, friendly repair, hostile/oversized rejection, Markdown import, preview and save');
  await click(new RegExp(config().actions[0].name));
  const first = page.getByRole('button', { name: new RegExp(config().actions[0].name) }); assert.equal(await first.isDisabled(), true);
  await page.reload(); await heading('Practice Lab'); assert.equal(await first.isDisabled(), true);
  await click(new RegExp(config().actions[1].name));
  await click('WEEK'); assert.ok((await page.locator('main').innerText()).includes('1 day worked'));
  await click('PROGRESS'); await click('Mark done'); await click('HISTORY'); assert.ok((await page.locator('main').innerText()).includes(config().actions[0].name));
  await click('TODAY'); await page.screenshot({ path: new URL('today-mobile.png', output).pathname.replace(/^\/(?=[A-Za-z]:)/, ''), fullPage: true });
  pass('Local action points, duplicate prevention, refresh, all four tracker views and milestone completion');
  await page.getByRole('button', { name: 'Backup & settings', exact: true }).click();
  const downloadPromise = page.waitForEvent('download'); await click('SAVE A BACKUP'); const download = await downloadPromise;
  const backupPath = new URL('backup.json', output).pathname.replace(/^\/(?=[A-Za-z]:)/, ''); await download.saveAs(backupPath);
  const before = await page.evaluate(() => localStorage.getItem('universalGoalTracker:state:v1'));
  await page.getByLabel('RESTORE A BACKUP', { exact: true }).setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{broken') });
  await page.getByRole('status').filter({ hasText: 'This backup could not be restored' }).waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('universalGoalTracker:state:v1')), before);
  await click('RESET MY TRACKER'); await page.getByRole('dialog').waitFor(); await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(() => localStorage.getItem('universalGoalTracker:state:v1')), before);
  await click('RESET MY TRACKER'); await click('YES, ERASE MY TRACKER'); await heading('Build Your Own Goal Tracker');
  await page.getByRole('button', { name: 'Backup & settings', exact: true }).click();
  await page.getByLabel('RESTORE A BACKUP', { exact: true }).setInputFiles(backupPath); await page.getByRole('dialog').waitFor();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('universalGoalTracker:state:v1')).trackerConfig), null);
  await click('RESTORE THIS BACKUP'); await heading('Practice Lab');
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('universalGoalTracker:state:v1')).actionHistory.length), 2);
  pass('Downloaded backup, invalid restore preservation, reset cancel/confirm, restore preview/confirm');
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.reload(); await heading('Practice Lab');
  await context.setOffline(true); await page.reload(); await heading('Practice Lab');
  await click(new RegExp(config().actions[2].name));
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('universalGoalTracker:state:v1')).actionHistory.length), 3);
  await page.close(); const reopened = await context.newPage(); reopened.on('pageerror', e => errors.push(e.message)); await reopened.goto(url);
  await reopened.getByRole('heading', { name: 'Practice Lab', exact: true }).waitFor();
  assert.equal(await reopened.evaluate(() => JSON.parse(localStorage.getItem('universalGoalTracker:state:v1')).actionHistory.length), 3);
  assert.equal(await reopened.locator('.action-card:disabled').count(), 3);
  pass('Real service worker, offline reload, offline actions and closing/reopening the app');
  await context.setOffline(false);
  await reopened.setViewportSize({ width: 1280, height: 900 });
  await reopened.screenshot({ path: new URL('today-desktop.png', output).pathname.replace(/^\/(?=[A-Za-z]:)/, ''), fullPage: true });
  assert.equal(await reopened.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  const assets = new Set(['', 'index.html', 'app.js', 'core.js', 'styles.css', 'pwa.js', 'sw.js', 'manifest.webmanifest', 'icon-192.png', 'icon-512.png']);
  for (const r of requests) { assert.equal(r.method, 'GET'); assert.equal(r.body, null); assert.equal(new URL(r.url).origin, new URL(url).origin); assert.ok(assets.has(new URL(r.url).pathname.split('/').pop()), r.url); }
  assert.deepEqual(errors, []);
  pass('Desktop layout, no JavaScript errors, and only local static GET requests with no tracker payloads');
  await fs.writeFile(new URL('browser-results.json', output), JSON.stringify({ results, errors, requestCount: requests.length }, null, 2));
  console.log(`Browser acceptance passed: ${results.length} groups.`);
} finally { await context?.close(); await browser.close(); await new Promise(resolve => server.close(resolve)); }
